# .terraform-docs.yml
content: |-
  {{ .Header }}

  ### Module Sagemaker Model

  {{ .Footer }}
  {{ .Inputs }}
  {{ .Modules }}
  {{ .Outputs }}
  {{ .Providers }}
  {{ .Requirements }}
  {{ .Resources }}
