# .terraform-docs.yml
content: |-
  {{ .Header }}

  ### Model Package with Single Model 

  ```hcl
  {{ include "examples/model-package-with-single-model/main.tf" }}
  ```

  {{ .Inputs }}

  {{ .Outputs }}